CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(15) NOT NULL UNIQUE,
    email VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(80) NOT NULL
);

ALTER TABLE users ADD COLUMN loggedin BOOLEAN SET DEFAULT FALSE;

ALTER TABLE users ADD COLUMN loggedin BOOLEAN;

ALTER TABLE users ALTER COLUMN loggedin SET DEFAULT FALSE;

ALTER TABLE users ALTER COLUMN loggedin SET NOT NULL;

SELECT * 