CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR NOT NULL,
    password VARCHAR NOT NULL
);

ALTER TABLE users ADD COLUMN loggedin BOOLEAN SET DEFAULT FALSE;

ALTER TABLE users ADD COLUMN loggedin BOOLEAN;

ALTER TABLE users ALTER COLUMN loggedin SET DEFAULT FALSE;

ALTER TABLE users ALTER COLUMN loggedin SET NOT NULL;
